apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/therajora/gitops-cluster
  username: therajora
  password: YOUR_GITHUB_TOKEN_HERE